# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

# Keep tool versions in sync with the versions in requirements-dev.txt
minimum_pre_commit_version: 2.13.0
default_language_version:
    python: python3
repos:
  - repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
      - id: black
  - repo: https://gitlab.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        additional_dependencies: [pep8-naming, flake8-bugbear, flake8-print]
  - repo: https://github.com/timothycrosley/isort
    rev: 5.10.1
    hooks:
      - id: isort
