
inherits:
  - strictness_medium

frosted:
  disable:
    - W101

mccabe:
  disable:
    - MC0001

pylint:
  disable:
    - C0301
    - C1001
    - E1101
    - R0401
    - R0912
    - R0914
    - W0221
    - W0311
    - W0613
    - W0622

pep8:
  disable:
    - E501

