DEBUG=1

# 1 = migrations will be applied during startup
APPLY_MIGRATIONS=1

# 1 = an admin user will be created during startup
CREATE_ADMIN_USER=1

# The password of the created admin user. If not given, a password will be generated.
ADMIN_USER_PASSWORD=

# 1 = add the initial page content to the database during startup
ADD_INITIAL_CONTENT=1

# The "from" address when the app sends emails
HKM_DEFAULT_FROM_EMAIL=no-reply@hel.ninja

# Comma-separated list of email addresses where the app will send feedback
HKM_FEEDBACK_NOTIFICATION_EMAILS=dummy-address@hel.ninja

# Uncomment this if you want to send emails using Mailgun. The app defaults to
# console logging otherwise.
#EMAIL_BACKEND=anymail.backends.mailgun.EmailBackend

# Mailgun configuration (fill these if you want to actually send emails)
MAIL_MAILGUN_KEY=
MAIL_MAILGUN_DOMAIN=
MAIL_MAILGUN_API=

# Level of logging. Defaults to ERROR in settings.py
LOG_LEVEL=DEBUG

# How many days will the password reset link be valid. Defaults to 1 day in settings.
PASSWORD_RESET_TIMEOUT=86400

# Controls whether the "feedback processing is congested" message is displayed or not. Defaults to False.
ENABLE_FEEDBACK_CONGESTION_MSG=
