# flake8: noqa
# https://api.finna.fi/v1/search?lookfor=torni&filter%5B%5D=format%3A%220%2FImage%2F%22&filter%5B%5D=building%3A%220%2FHKM%2F%22&filter%5B%5D=online_boolean%3A%221%22&page=1&limit=2&lng=fi&field%5B%5D=id&field%5B%5D=authors&field%5B%5D=buildings&field%5B%5D=formats&field%5B%5D=genres&field%5B%5D=humanReadablePublicationDates&field%5B%5D=imageRights&field%5B%5D=images&field%5B%5D=institutions&field%5B%5D=languages&field%5B%5D=originalLanguages&field%5B%5D=presenters&field%5B%5D=publicationDates&field%5B%5D=rating&field%5B%5D=series&field%5B%5D=subjects&field%5B%5D=summary&field%5B%5D=title&field%5B%5D=year&field%5B%5D=rawData
SEARCH_RESPONSE = {
    "resultCount": 1899,
    "records": [
        {
            "id": "hkm.HKMS000005:000001pt",
            "authors": {
                "primary": {"Bonin Volker von, valokuvaaja": {"role": ["-"]}},
                "secondary": [],
                "corporate": [],
            },
            "buildings": [
                {"value": "0/HKM/", "translated": "Helsingin kaupunginmuseo"}
            ],
            "formats": [
                {"value": "0/Image/", "translated": "Kuva"},
                {"value": "1/Image/Photo/", "translated": "Valokuva"},
            ],
            "genres": [],
            "humanReadablePublicationDates": [],
            "imageRights": {
                "copyright": "CC BY 4.0",
                "link": "http://creativecommons.org/licenses/by/4.0/deed.fi",
            },
            "images": [
                "/Cover/Show?id=hkm.HKMS000005%3A000001pt&index=0&size=large&source=Solr"
            ],
            "institutions": [
                {
                    "value": "Helsingin kaupunginmuseo",
                    "translated": "Helsingin kaupunginmuseo",
                }
            ],
            "languages": [],
            "originalLanguages": [],
            "presenters": [],
            "publicationDates": [],
            "rating": {"average": 0, "count": 0},
            "series": [],
            "subjects": [
                ["stadionit"],
                ["urheilurakennukset"],
                ["arkkitehtuuri"],
                ["funktionalismi"],
                ["Helsinki, Paavo Nurmen tie 1"],
                ["1952"],
            ],
            "summary": ["negatiivi, filmi, mv"],
            "title": "Olympiastadionin torni.",
            "year": "1952",
            "rawData": {
                "record_format": "lido",
                "title_full": "Olympiastadionin torni.",
                "title_fullStr": "Olympiastadionin torni.",
                "title_full_unstemmed": "Olympiastadionin torni.",
                "title_short": "Olympiastadionin torni.",
                "title": "Olympiastadionin torni.",
                "title_txtP": "Olympiastadionin torni.",
                "description": "negatiivi, filmi, mv",
                "format": [
                    {"value": "0/Image/", "translated": "Kuva"},
                    {"value": "1/Image/Photo/", "translated": "Valokuva"},
                ],
                "author": ["Bonin Volker von, valokuvaaja"],
                "author_sort": "Bonin Volker von, valokuvaaja",
                "topic": [
                    "stadionit",
                    "urheilurakennukset",
                    "arkkitehtuuri",
                    "funktionalismi",
                ],
                "era": ["1952"],
                "geographic": ["Helsinki, Paavo Nurmen tie 1"],
                "thumbnail": "http://89.250.56.218/KDKDataProvider/down.load?dataType=preview&uniqueId=000001pt&pKey=000001pt1605607644632&pValue=2fa14a86110097abfc1e9683e0ff9a30",
                "measurements": ["6x6"],
                "classification_txt_mv": [
                    "27 Urheilurakennukset ja -kentät",
                    "345 virkistystoimintaan liittyvät rakennukset",
                    "mv",
                    "neliö",
                    "arkkitehtuuri",
                    "negatiivi",
                ],
                "main_date": "1952-01-01T00:00:00Z",
                "search_daterange_mv": ["[1952-01-01 TO 1952-12-31]"],
                "creation_daterange": "[1952-01-01 TO 1952-12-31]",
                "location_geo": [
                    "POINT(24.92604 60.1863242)",
                    "ENVELOPE(24.9256447, 24.9288928, 60.1880948, 60.1858551)",
                ],
                "center_coords": "24.92604 60.1863242",
                "author_facet": ["Bonin Volker von"],
                "id": "hkm.HKMS000005:000001pt",
                "first_indexed": "2014-02-18T14:58:45Z",
                "last_indexed": "2022-01-13T21:07:54Z",
                "classification_str_mv": [
                    "27 Urheilurakennukset ja -kentät",
                    "345 virkistystoimintaan liittyvät rakennukset",
                    "arkkitehtuuri",
                    "mv",
                    "negatiivi",
                    "neliö",
                ],
                "building": [
                    {"value": "0/HKM/", "translated": "Helsingin kaupunginmuseo"}
                ],
                "usage_rights_str_mv": ["usage_B", "usage_C", "usage_D", "usage_E"],
                "institution": ["Helsingin kaupunginmuseo"],
                "sector_str_mv": [{"value": "0/mus/", "translated": "Museo"}],
                "topic_facet": [
                    "arkkitehtuuri",
                    "funktionalismi",
                    "stadionit",
                    "urheilurakennukset",
                ],
                "online_boolean": 1,
                "hires_image_boolean": 1,
                "online_str_mv": ["hkm"],
                "identifier": ["N210139"],
                "free_online_str_mv": ["hkm"],
                "source_str_mv": ["hkm"],
                "work_keys_str_mv": ["AT boninvolkervon olympiastadionintorni"],
                "geographic_facet": ["Helsinki", "Helsinki, Paavo Nurmen tie 1"],
                "rights": ["Helsingin kaupunginmuseo"],
                "main_date_str": "1952",
                "era_facet": ["1952"],
                "photographer_str_mv": ["Bonin Volker von"],
                "title_sort": "Olympiastadionin torni.",
                "free_online_boolean": 1,
                "format_ext_str_mv": [
                    {"value": "0/Image/", "translated": "Kuva"},
                    {"value": "1/Image/Photo/", "translated": "Valokuva"},
                ],
                "datasource_str_mv": ["hkm"],
                "_version_": 1722501275922202624,
                "hires_image_str_mv": ["hkm"],
            },
        },
        {
            "id": "hkm.HKMS000005:000001pu",
            "authors": {
                "primary": {"Bonin Volker von, valokuvaaja": {"role": ["-"]}},
                "secondary": [],
                "corporate": [],
            },
            "buildings": [
                {"value": "0/HKM/", "translated": "Helsingin kaupunginmuseo"}
            ],
            "formats": [
                {"value": "0/Image/", "translated": "Kuva"},
                {"value": "1/Image/Photo/", "translated": "Valokuva"},
            ],
            "genres": [],
            "humanReadablePublicationDates": [],
            "imageRights": {
                "copyright": "CC BY 4.0",
                "link": "http://creativecommons.org/licenses/by/4.0/deed.fi",
            },
            "images": [
                "/Cover/Show?id=hkm.HKMS000005%3A000001pu&index=0&size=large&source=Solr"
            ],
            "institutions": [
                {
                    "value": "Helsingin kaupunginmuseo",
                    "translated": "Helsingin kaupunginmuseo",
                }
            ],
            "languages": [],
            "originalLanguages": [],
            "presenters": [],
            "publicationDates": [],
            "rating": {"average": 0, "count": 0},
            "series": [],
            "subjects": [
                ["stadionit"],
                ["urheilurakennukset"],
                ["arkkitehtuuri"],
                ["funktionalismi"],
                ["Helsinki, Paavo Nurmen tie 1"],
                ["1952"],
            ],
            "summary": ["negatiivi, filmi, mv"],
            "title": "Olympiastadionin torni.",
            "year": "1952",
            "rawData": {
                "record_format": "lido",
                "title_full": "Olympiastadionin torni.",
                "title_fullStr": "Olympiastadionin torni.",
                "title_full_unstemmed": "Olympiastadionin torni.",
                "title_short": "Olympiastadionin torni.",
                "title": "Olympiastadionin torni.",
                "title_txtP": "Olympiastadionin torni.",
                "description": "negatiivi, filmi, mv",
                "format": [
                    {"value": "0/Image/", "translated": "Kuva"},
                    {"value": "1/Image/Photo/", "translated": "Valokuva"},
                ],
                "author": ["Bonin Volker von, valokuvaaja"],
                "author_sort": "Bonin Volker von, valokuvaaja",
                "topic": [
                    "stadionit",
                    "urheilurakennukset",
                    "arkkitehtuuri",
                    "funktionalismi",
                ],
                "era": ["1952"],
                "geographic": ["Helsinki, Paavo Nurmen tie 1"],
                "thumbnail": "http://89.250.56.218/KDKDataProvider/down.load?dataType=preview&uniqueId=000001pu&pKey=000001pu1605607644630&pValue=3590a17dffdd8ea624fc8138f6850d88",
                "measurements": ["6x6"],
                "classification_txt_mv": [
                    "27 Urheilurakennukset ja -kentät",
                    "345 virkistystoimintaan liittyvät rakennukset",
                    "mv",
                    "neliö",
                    "arkkitehtuuri",
                    "negatiivi",
                ],
                "main_date": "1952-01-01T00:00:00Z",
                "search_daterange_mv": ["[1952-01-01 TO 1952-12-31]"],
                "creation_daterange": "[1952-01-01 TO 1952-12-31]",
                "location_geo": [
                    "POINT(24.92604 60.1863242)",
                    "ENVELOPE(24.9256447, 24.9288928, 60.1880948, 60.1858551)",
                ],
                "center_coords": "24.92604 60.1863242",
                "author_facet": ["Bonin Volker von"],
                "id": "hkm.HKMS000005:000001pu",
                "first_indexed": "2014-02-18T14:58:45Z",
                "last_indexed": "2022-01-13T21:07:54Z",
                "classification_str_mv": [
                    "27 Urheilurakennukset ja -kentät",
                    "345 virkistystoimintaan liittyvät rakennukset",
                    "arkkitehtuuri",
                    "mv",
                    "negatiivi",
                    "neliö",
                ],
                "building": [
                    {"value": "0/HKM/", "translated": "Helsingin kaupunginmuseo"}
                ],
                "usage_rights_str_mv": ["usage_B", "usage_C", "usage_D", "usage_E"],
                "institution": ["Helsingin kaupunginmuseo"],
                "sector_str_mv": [{"value": "0/mus/", "translated": "Museo"}],
                "topic_facet": [
                    "arkkitehtuuri",
                    "funktionalismi",
                    "stadionit",
                    "urheilurakennukset",
                ],
                "online_boolean": 1,
                "hires_image_boolean": 1,
                "online_str_mv": ["hkm"],
                "identifier": ["N210140"],
                "free_online_str_mv": ["hkm"],
                "source_str_mv": ["hkm"],
                "work_keys_str_mv": ["AT boninvolkervon olympiastadionintorni"],
                "geographic_facet": ["Helsinki", "Helsinki, Paavo Nurmen tie 1"],
                "rights": ["Helsingin kaupunginmuseo"],
                "main_date_str": "1952",
                "era_facet": ["1952"],
                "photographer_str_mv": ["Bonin Volker von"],
                "title_sort": "Olympiastadionin torni.",
                "free_online_boolean": 1,
                "format_ext_str_mv": [
                    {"value": "0/Image/", "translated": "Kuva"},
                    {"value": "1/Image/Photo/", "translated": "Valokuva"},
                ],
                "datasource_str_mv": ["hkm"],
                "_version_": 1722501275923251201,
                "hires_image_str_mv": ["hkm"],
            },
        },
    ],
    "status": "OK",
}

# https://api.finna.fi/v1/record?id%5B%5D=hkm.HKMS000005%3Akm003mrk&field%5B%5D=id&field%5B%5D=authors&field%5B%5D=buildings&field%5B%5D=formats&field%5B%5D=genres&field%5B%5D=humanReadablePublicationDates&field%5B%5D=imageRights&field%5B%5D=images&field%5B%5D=institutions&field%5B%5D=languages&field%5B%5D=originalLanguages&field%5B%5D=presenters&field%5B%5D=publicationDates&field%5B%5D=rating&field%5B%5D=series&field%5B%5D=subjects&field%5B%5D=summary&field%5B%5D=title&field%5B%5D=year&field%5B%5D=rawData
RECORD_RESPONSE = {
    "resultCount": 1,
    "records": [
        {
            "id": "hkm.HKMS000005:km003mrk",
            "authors": {
                "primary": {"Foto Roos, valokuvaaja": {"role": ["-"]}},
                "secondary": [],
                "corporate": [],
            },
            "buildings": [
                {"value": "0/HKM/", "translated": "Helsingin kaupunginmuseo"}
            ],
            "formats": [
                {"value": "0/Image/", "translated": "Kuva"},
                {"value": "1/Image/Photo/", "translated": "Valokuva"},
            ],
            "genres": [],
            "humanReadablePublicationDates": [],
            "imageRights": {
                "copyright": "CC BY 4.0",
                "link": "http://creativecommons.org/licenses/by/4.0/deed.fi",
            },
            "images": [
                "/Cover/Show?id=hkm.HKMS000005%3Akm003mrk&index=0&size=large&source=Solr"
            ],
            "institutions": [
                {
                    "value": "Helsingin kaupunginmuseo",
                    "translated": "Helsingin kaupunginmuseo",
                }
            ],
            "languages": [],
            "originalLanguages": [],
            "presenters": [],
            "publicationDates": [],
            "rating": {"average": 0, "count": 0},
            "series": [],
            "subjects": [
                ["hotellit"],
                ["interiöörit"],
                ["kattoikkunat"],
                ["kupolit"],
                ["valaisimet seinävalaisimet"],
                ["takat"],
                ["matot"],
                ["parketit"],
                ["Helsinki, Kalevankatu 5 - Yrjönkatu 26"],
                ["1930 n"],
            ],
            "summary": [
                "Hotelli Torni. Kalevankatu 5 - Yrjönkatu 26. Seurusteluhuone. -- negatiivi vedos, lasi paperi, mv"
            ],
            "title": "Hotelli Torni",
            "year": "1930",
            "rawData": {
                "record_format": "lido",
                "description": "Hotelli Torni. Kalevankatu 5 - Yrjönkatu 26. Seurusteluhuone. -- negatiivi vedos, lasi paperi, mv",
                "title_full": "Hotelli Torni",
                "title_fullStr": "Hotelli Torni",
                "title_full_unstemmed": "Hotelli Torni",
                "title_short": "Hotelli Torni",
                "title": "Hotelli Torni",
                "title_txtP": "Hotelli Torni",
                "title_alt": [
                    "Hotelli Torni. Kalevankatu 5 - Yrjönkatu 26. Seurusteluhuone."
                ],
                "format": [
                    {"value": "0/Image/", "translated": "Kuva"},
                    {"value": "1/Image/Photo/", "translated": "Valokuva"},
                ],
                "author": ["Foto Roos, valokuvaaja"],
                "author_sort": "Foto Roos, valokuvaaja",
                "topic": [
                    "hotellit",
                    "interiöörit",
                    "kattoikkunat",
                    "kupolit",
                    "valaisimet seinävalaisimet",
                    "takat",
                    "matot",
                    "parketit",
                ],
                "era": ["1930 n"],
                "geographic": ["Helsinki, Kalevankatu 5 - Yrjönkatu 26"],
                "thumbnail": "http://89.250.56.218/KDKDataProvider/down.load?dataType=preview&uniqueId=km003mrk&pKey=km003mrk1605607431416&pValue=fdd13e2bb0e1f2066b077bd84fbd4d18",
                "measurements": ["13x18 18x24"],
                "classification_txt_mv": [
                    "67 hotellit ja ravintolat",
                    "485 Matkailupalvelut",
                    "mv",
                    "vaaka",
                    "interiööri",
                    "negatiivi vedos",
                ],
                "main_date": "1930-01-01T00:00:00Z",
                "search_daterange_mv": ["[1930-01-01 TO 1930-12-31]"],
                "creation_daterange": "[1930-01-01 TO 1930-12-31]",
                "author_facet": ["Foto Roos"],
                "id": "hkm.HKMS000005:km003mrk",
                "first_indexed": "2014-06-17T20:07:15Z",
                "last_indexed": "2022-01-13T21:07:27Z",
                "classification_str_mv": [
                    "485 Matkailupalvelut",
                    "67 hotellit ja ravintolat",
                    "interiööri",
                    "mv",
                    "negatiivi vedos",
                    "vaaka",
                ],
                "building": [
                    {"value": "0/HKM/", "translated": "Helsingin kaupunginmuseo"}
                ],
                "usage_rights_str_mv": ["usage_B", "usage_C", "usage_D", "usage_E"],
                "institution": ["Helsingin kaupunginmuseo"],
                "sector_str_mv": [{"value": "0/mus/", "translated": "Museo"}],
                "topic_facet": [
                    "hotellit",
                    "interiöörit",
                    "kattoikkunat",
                    "kupolit",
                    "matot",
                    "parketit",
                    "takat",
                    "valaisimet seinävalaisimet",
                ],
                "online_boolean": 1,
                "hires_image_boolean": 1,
                "online_str_mv": ["hkm"],
                "identifier": ["N43846"],
                "free_online_str_mv": ["hkm"],
                "source_str_mv": ["hkm"],
                "work_keys_str_mv": [
                    "AT fotoroos hotellitornikalevankatu5yrjönkatu26seurusteluhuone"
                ],
                "geographic_facet": [
                    "Helsinki",
                    "Helsinki, Kalevankatu 5 - Yrjönkatu 26",
                ],
                "rights": ["Helsingin kaupunginmuseo"],
                "main_date_str": "1930",
                "era_facet": ["1930 n"],
                "photographer_str_mv": ["Foto Roos"],
                "title_sort": "Hotelli Torni. Kalevankatu 5 - Yrjönkatu 26. Seurusteluhuone.",
                "free_online_boolean": 1,
                "format_ext_str_mv": [
                    {"value": "0/Image/", "translated": "Kuva"},
                    {"value": "1/Image/Photo/", "translated": "Valokuva"},
                ],
                "datasource_str_mv": ["hkm"],
                "_version_": 1722501493734506496,
                "hires_image_str_mv": ["hkm"],
            },
        }
    ],
    "status": "OK",
}

# https://api.finna.fi/v1/search?lookfor=torni&filter%5B%5D=format%3A%220%2FImage%2F%22&filter%5B%5D=building%3A%220%2FHKM%2F%22&filter%5B%5D=online_boolean%3A%221%22&limit=0&lng=fi&facet%5B%5D=author_facet&facet%5B%5D=collection&facet%5B%5D=genre_facet&facet%5B%5D=main_date_str&facet%5B%5D=category_str_mv
FACETS_RESPONSE = {
    "resultCount": 1899,
    "facets": {
        "author_facet": [
            {
                "value": "Rista Simo SER",
                "translated": "Rista Simo SER",
                "count": 247,
                "href": "?limit=0&filter%5B%5D=format%3A%220%2FImage%2F%22&filter%5B%5D=building%3A%220%2FHKM%2F%22&filter%5B%5D=online_boolean%3A%221%22&filter%5B%5D=author_facet%3A%22Rista+Simo+SER%22&lookfor=torni&type=AllFields",
            },
            {
                "value": "Tuntematon",
                "translated": "Tuntematon",
                "count": 223,
                "href": "?limit=0&filter%5B%5D=format%3A%220%2FImage%2F%22&filter%5B%5D=building%3A%220%2FHKM%2F%22&filter%5B%5D=online_boolean%3A%221%22&filter%5B%5D=author_facet%3A%22Tuntematon%22&lookfor=torni&type=AllFields",
            },
            {
                "value": "Rista Eeva SER",
                "translated": "Rista Eeva SER",
                "count": 191,
                "href": "?limit=0&filter%5B%5D=format%3A%220%2FImage%2F%22&filter%5B%5D=building%3A%220%2FHKM%2F%22&filter%5B%5D=online_boolean%3A%221%22&filter%5B%5D=author_facet%3A%22Rista+Eeva+SER%22&lookfor=torni&type=AllFields",
            },
            {
                "value": "Hakli Kari",
                "translated": "Hakli Kari",
                "count": 117,
                "href": "?limit=0&filter%5B%5D=format%3A%220%2FImage%2F%22&filter%5B%5D=building%3A%220%2FHKM%2F%22&filter%5B%5D=online_boolean%3A%221%22&filter%5B%5D=author_facet%3A%22Hakli+Kari%22&lookfor=torni&type=AllFields",
            },
            {
                "value": "Nurmi Juho HKM",
                "translated": "Nurmi Juho HKM",
                "count": 79,
                "href": "?limit=0&filter%5B%5D=format%3A%220%2FImage%2F%22&filter%5B%5D=building%3A%220%2FHKM%2F%22&filter%5B%5D=online_boolean%3A%221%22&filter%5B%5D=author_facet%3A%22Nurmi+Juho+HKM%22&lookfor=torni&type=AllFields",
            },
            {
                "value": "Grünberg Constantin",
                "translated": "Grünberg Constantin",
                "count": 62,
                "href": "?limit=0&filter%5B%5D=format%3A%220%2FImage%2F%22&filter%5B%5D=building%3A%220%2FHKM%2F%22&filter%5B%5D=online_boolean%3A%221%22&filter%5B%5D=author_facet%3A%22Gr%C3%BCnberg+Constantin%22&lookfor=torni&type=AllFields",
            },
            {
                "value": "Bonin Volker von",
                "translated": "Bonin Volker von",
                "count": 58,
                "href": "?limit=0&filter%5B%5D=format%3A%220%2FImage%2F%22&filter%5B%5D=building%3A%220%2FHKM%2F%22&filter%5B%5D=online_boolean%3A%221%22&filter%5B%5D=author_facet%3A%22Bonin+Volker+von%22&lookfor=torni&type=AllFields",
            },
            {
                "value": "Heinonen Eino",
                "translated": "Heinonen Eino",
                "count": 44,
                "href": "?limit=0&filter%5B%5D=format%3A%220%2FImage%2F%22&filter%5B%5D=building%3A%220%2FHKM%2F%22&filter%5B%5D=online_boolean%3A%221%22&filter%5B%5D=author_facet%3A%22Heinonen+Eino%22&lookfor=torni&type=AllFields",
            },
            {
                "value": "Eweis Yehia HKM",
                "translated": "Eweis Yehia HKM",
                "count": 43,
                "href": "?limit=0&filter%5B%5D=format%3A%220%2FImage%2F%22&filter%5B%5D=building%3A%220%2FHKM%2F%22&filter%5B%5D=online_boolean%3A%221%22&filter%5B%5D=author_facet%3A%22Eweis+Yehia+HKM%22&lookfor=torni&type=AllFields",
            },
            {
                "value": "Hoffers Eugen",
                "translated": "Hoffers Eugen",
                "count": 43,
                "href": "?limit=0&filter%5B%5D=format%3A%220%2FImage%2F%22&filter%5B%5D=building%3A%220%2FHKM%2F%22&filter%5B%5D=online_boolean%3A%221%22&filter%5B%5D=author_facet%3A%22Hoffers+Eugen%22&lookfor=torni&type=AllFields",
            },
            {
                "value": "Ahola Harri",
                "translated": "Ahola Harri",
                "count": 42,
                "href": "?limit=0&filter%5B%5D=format%3A%220%2FImage%2F%22&filter%5B%5D=building%3A%220%2FHKM%2F%22&filter%5B%5D=online_boolean%3A%221%22&filter%5B%5D=author_facet%3A%22Ahola+Harri%22&lookfor=torni&type=AllFields",
            },
            {
                "value": "Brander Signe HKM",
                "translated": "Brander Signe HKM",
                "count": 41,
                "href": "?limit=0&filter%5B%5D=format%3A%220%2FImage%2F%22&filter%5B%5D=building%3A%220%2FHKM%2F%22&filter%5B%5D=online_boolean%3A%221%22&filter%5B%5D=author_facet%3A%22Brander+Signe+HKM%22&lookfor=torni&type=AllFields",
            },
            {
                "value": "Rosenbröijer A. E.",
                "translated": "Rosenbröijer A. E.",
                "count": 32,
                "href": "?limit=0&filter%5B%5D=format%3A%220%2FImage%2F%22&filter%5B%5D=building%3A%220%2FHKM%2F%22&filter%5B%5D=online_boolean%3A%221%22&filter%5B%5D=author_facet%3A%22Rosenbr%C3%B6ijer+A.+E.%22&lookfor=torni&type=AllFields",
            },
            {
                "value": "Eweis Yehia",
                "translated": "Eweis Yehia",
                "count": 27,
                "href": "?limit=0&filter%5B%5D=format%3A%220%2FImage%2F%22&filter%5B%5D=building%3A%220%2FHKM%2F%22&filter%5B%5D=online_boolean%3A%221%22&filter%5B%5D=author_facet%3A%22Eweis+Yehia%22&lookfor=torni&type=AllFields",
            },
            {
                "value": "SKY-FOTO Möller",
                "translated": "SKY-FOTO Möller",
                "count": 27,
                "href": "?limit=0&filter%5B%5D=format%3A%220%2FImage%2F%22&filter%5B%5D=building%3A%220%2FHKM%2F%22&filter%5B%5D=online_boolean%3A%221%22&filter%5B%5D=author_facet%3A%22SKY-FOTO+M%C3%B6ller%22&lookfor=torni&type=AllFields",
            },
            {
                "value": "Sundström Olof",
                "translated": "Sundström Olof",
                "count": 27,
                "href": "?limit=0&filter%5B%5D=format%3A%220%2FImage%2F%22&filter%5B%5D=building%3A%220%2FHKM%2F%22&filter%5B%5D=online_boolean%3A%221%22&filter%5B%5D=author_facet%3A%22Sundstr%C3%B6m+Olof%22&lookfor=torni&type=AllFields",
            },
            {
                "value": "Timiriasew Ivan",
                "translated": "Timiriasew Ivan",
                "count": 23,
                "href": "?limit=0&filter%5B%5D=format%3A%220%2FImage%2F%22&filter%5B%5D=building%3A%220%2FHKM%2F%22&filter%5B%5D=online_boolean%3A%221%22&filter%5B%5D=author_facet%3A%22Timiriasew+Ivan%22&lookfor=torni&type=AllFields",
            },
            {
                "value": "Vyhtinen Pekka",
                "translated": "Vyhtinen Pekka",
                "count": 21,
                "href": "?limit=0&filter%5B%5D=format%3A%220%2FImage%2F%22&filter%5B%5D=building%3A%220%2FHKM%2F%22&filter%5B%5D=online_boolean%3A%221%22&filter%5B%5D=author_facet%3A%22Vyhtinen+Pekka%22&lookfor=torni&type=AllFields",
            },
            {
                "value": "Kajantie Arvo",
                "translated": "Kajantie Arvo",
                "count": 20,
                "href": "?limit=0&filter%5B%5D=format%3A%220%2FImage%2F%22&filter%5B%5D=building%3A%220%2FHKM%2F%22&filter%5B%5D=online_boolean%3A%221%22&filter%5B%5D=author_facet%3A%22Kajantie+Arvo%22&lookfor=torni&type=AllFields",
            },
            {
                "value": "Kiuru Sakari HKM",
                "translated": "Kiuru Sakari HKM",
                "count": 20,
                "href": "?limit=0&filter%5B%5D=format%3A%220%2FImage%2F%22&filter%5B%5D=building%3A%220%2FHKM%2F%22&filter%5B%5D=online_boolean%3A%221%22&filter%5B%5D=author_facet%3A%22Kiuru+Sakari+HKM%22&lookfor=torni&type=AllFields",
            },
            {
                "value": "Alanco Jan HKM",
                "translated": "Alanco Jan HKM",
                "count": 17,
                "href": "?limit=0&filter%5B%5D=format%3A%220%2FImage%2F%22&filter%5B%5D=building%3A%220%2FHKM%2F%22&filter%5B%5D=online_boolean%3A%221%22&filter%5B%5D=author_facet%3A%22Alanco+Jan+HKM%22&lookfor=torni&type=AllFields",
            },
            {
                "value": "Pälsi Sakari",
                "translated": "Pälsi Sakari",
                "count": 16,
                "href": "?limit=0&filter%5B%5D=format%3A%220%2FImage%2F%22&filter%5B%5D=building%3A%220%2FHKM%2F%22&filter%5B%5D=online_boolean%3A%221%22&filter%5B%5D=author_facet%3A%22P%C3%A4lsi+Sakari%22&lookfor=torni&type=AllFields",
            },
            {
                "value": "Wesander Merja",
                "translated": "Wesander Merja",
                "count": 16,
                "href": "?limit=0&filter%5B%5D=format%3A%220%2FImage%2F%22&filter%5B%5D=building%3A%220%2FHKM%2F%22&filter%5B%5D=online_boolean%3A%221%22&filter%5B%5D=author_facet%3A%22Wesander+Merja%22&lookfor=torni&type=AllFields",
            },
            {
                "value": "Erico",
                "translated": "Erico",
                "count": 14,
                "href": "?limit=0&filter%5B%5D=format%3A%220%2FImage%2F%22&filter%5B%5D=building%3A%220%2FHKM%2F%22&filter%5B%5D=online_boolean%3A%221%22&filter%5B%5D=author_facet%3A%22Erico%22&lookfor=torni&type=AllFields",
            },
            {
                "value": "Similä Matti",
                "translated": "Similä Matti",
                "count": 14,
                "href": "?limit=0&filter%5B%5D=format%3A%220%2FImage%2F%22&filter%5B%5D=building%3A%220%2FHKM%2F%22&filter%5B%5D=online_boolean%3A%221%22&filter%5B%5D=author_facet%3A%22Simil%C3%A4+Matti%22&lookfor=torni&type=AllFields",
            },
            {
                "value": "Welin P O",
                "translated": "Welin P O",
                "count": 14,
                "href": "?limit=0&filter%5B%5D=format%3A%220%2FImage%2F%22&filter%5B%5D=building%3A%220%2FHKM%2F%22&filter%5B%5D=online_boolean%3A%221%22&filter%5B%5D=author_facet%3A%22Welin+P+O%22&lookfor=torni&type=AllFields",
            },
            {
                "value": "tuntematon",
                "translated": "tuntematon",
                "count": 14,
                "href": "?limit=0&filter%5B%5D=format%3A%220%2FImage%2F%22&filter%5B%5D=building%3A%220%2FHKM%2F%22&filter%5B%5D=online_boolean%3A%221%22&filter%5B%5D=author_facet%3A%22tuntematon%22&lookfor=torni&type=AllFields",
            },
            {
                "value": "Aarnio Jalmari",
                "translated": "Aarnio Jalmari",
                "count": 12,
                "href": "?limit=0&filter%5B%5D=format%3A%220%2FImage%2F%22&filter%5B%5D=building%3A%220%2FHKM%2F%22&filter%5B%5D=online_boolean%3A%221%22&filter%5B%5D=author_facet%3A%22Aarnio+Jalmari%22&lookfor=torni&type=AllFields",
            },
            {
                "value": "Foto Roos",
                "translated": "Foto Roos",
                "count": 11,
                "href": "?limit=0&filter%5B%5D=format%3A%220%2FImage%2F%22&filter%5B%5D=building%3A%220%2FHKM%2F%22&filter%5B%5D=online_boolean%3A%221%22&filter%5B%5D=author_facet%3A%22Foto+Roos%22&lookfor=torni&type=AllFields",
            },
            {
                "value": "Havas Kalle",
                "translated": "Havas Kalle",
                "count": 11,
                "href": "?limit=0&filter%5B%5D=format%3A%220%2FImage%2F%22&filter%5B%5D=building%3A%220%2FHKM%2F%22&filter%5B%5D=online_boolean%3A%221%22&filter%5B%5D=author_facet%3A%22Havas+Kalle%22&lookfor=torni&type=AllFields",
            },
        ],
        "main_date_str": [
            {
                "value": "1970",
                "translated": "1970",
                "count": 291,
                "href": "?limit=0&filter%5B%5D=format%3A%220%2FImage%2F%22&filter%5B%5D=building%3A%220%2FHKM%2F%22&filter%5B%5D=online_boolean%3A%221%22&filter%5B%5D=main_date_str%3A%221970%22&lookfor=torni&type=AllFields",
            },
            {
                "value": "1950",
                "translated": "1950",
                "count": 80,
                "href": "?limit=0&filter%5B%5D=format%3A%220%2FImage%2F%22&filter%5B%5D=building%3A%220%2FHKM%2F%22&filter%5B%5D=online_boolean%3A%221%22&filter%5B%5D=main_date_str%3A%221950%22&lookfor=torni&type=AllFields",
            },
            {
                "value": "2019",
                "translated": "2019",
                "count": 80,
                "href": "?limit=0&filter%5B%5D=format%3A%220%2FImage%2F%22&filter%5B%5D=building%3A%220%2FHKM%2F%22&filter%5B%5D=online_boolean%3A%221%22&filter%5B%5D=main_date_str%3A%222019%22&lookfor=torni&type=AllFields",
            },
            {
                "value": "1930",
                "translated": "1930",
                "count": 73,
                "href": "?limit=0&filter%5B%5D=format%3A%220%2FImage%2F%22&filter%5B%5D=building%3A%220%2FHKM%2F%22&filter%5B%5D=online_boolean%3A%221%22&filter%5B%5D=main_date_str%3A%221930%22&lookfor=torni&type=AllFields",
            },
            {
                "value": "1972",
                "translated": "1972",
                "count": 66,
                "href": "?limit=0&filter%5B%5D=format%3A%220%2FImage%2F%22&filter%5B%5D=building%3A%220%2FHKM%2F%22&filter%5B%5D=online_boolean%3A%221%22&filter%5B%5D=main_date_str%3A%221972%22&lookfor=torni&type=AllFields",
            },
            {
                "value": "1960",
                "translated": "1960",
                "count": 58,
                "href": "?limit=0&filter%5B%5D=format%3A%220%2FImage%2F%22&filter%5B%5D=building%3A%220%2FHKM%2F%22&filter%5B%5D=online_boolean%3A%221%22&filter%5B%5D=main_date_str%3A%221960%22&lookfor=torni&type=AllFields",
            },
            {
                "value": "1971",
                "translated": "1971",
                "count": 58,
                "href": "?limit=0&filter%5B%5D=format%3A%220%2FImage%2F%22&filter%5B%5D=building%3A%220%2FHKM%2F%22&filter%5B%5D=online_boolean%3A%221%22&filter%5B%5D=main_date_str%3A%221971%22&lookfor=torni&type=AllFields",
            },
            {
                "value": "1987",
                "translated": "1987",
                "count": 57,
                "href": "?limit=0&filter%5B%5D=format%3A%220%2FImage%2F%22&filter%5B%5D=building%3A%220%2FHKM%2F%22&filter%5B%5D=online_boolean%3A%221%22&filter%5B%5D=main_date_str%3A%221987%22&lookfor=torni&type=AllFields",
            },
            {
                "value": "2008",
                "translated": "2008",
                "count": 49,
                "href": "?limit=0&filter%5B%5D=format%3A%220%2FImage%2F%22&filter%5B%5D=building%3A%220%2FHKM%2F%22&filter%5B%5D=online_boolean%3A%221%22&filter%5B%5D=main_date_str%3A%222008%22&lookfor=torni&type=AllFields",
            },
            {
                "value": "1973",
                "translated": "1973",
                "count": 42,
                "href": "?limit=0&filter%5B%5D=format%3A%220%2FImage%2F%22&filter%5B%5D=building%3A%220%2FHKM%2F%22&filter%5B%5D=online_boolean%3A%221%22&filter%5B%5D=main_date_str%3A%221973%22&lookfor=torni&type=AllFields",
            },
            {
                "value": "1900",
                "translated": "1900",
                "count": 38,
                "href": "?limit=0&filter%5B%5D=format%3A%220%2FImage%2F%22&filter%5B%5D=building%3A%220%2FHKM%2F%22&filter%5B%5D=online_boolean%3A%221%22&filter%5B%5D=main_date_str%3A%221900%22&lookfor=torni&type=AllFields",
            },
            {
                "value": "1890",
                "translated": "1890",
                "count": 37,
                "href": "?limit=0&filter%5B%5D=format%3A%220%2FImage%2F%22&filter%5B%5D=building%3A%220%2FHKM%2F%22&filter%5B%5D=online_boolean%3A%221%22&filter%5B%5D=main_date_str%3A%221890%22&lookfor=torni&type=AllFields",
            },
            {
                "value": "1982",
                "translated": "1982",
                "count": 36,
                "href": "?limit=0&filter%5B%5D=format%3A%220%2FImage%2F%22&filter%5B%5D=building%3A%220%2FHKM%2F%22&filter%5B%5D=online_boolean%3A%221%22&filter%5B%5D=main_date_str%3A%221982%22&lookfor=torni&type=AllFields",
            },
            {
                "value": "2020",
                "translated": "2020",
                "count": 35,
                "href": "?limit=0&filter%5B%5D=format%3A%220%2FImage%2F%22&filter%5B%5D=building%3A%220%2FHKM%2F%22&filter%5B%5D=online_boolean%3A%221%22&filter%5B%5D=main_date_str%3A%222020%22&lookfor=torni&type=AllFields",
            },
            {
                "value": "1975",
                "translated": "1975",
                "count": 31,
                "href": "?limit=0&filter%5B%5D=format%3A%220%2FImage%2F%22&filter%5B%5D=building%3A%220%2FHKM%2F%22&filter%5B%5D=online_boolean%3A%221%22&filter%5B%5D=main_date_str%3A%221975%22&lookfor=torni&type=AllFields",
            },
            {
                "value": "1910",
                "translated": "1910",
                "count": 29,
                "href": "?limit=0&filter%5B%5D=format%3A%220%2FImage%2F%22&filter%5B%5D=building%3A%220%2FHKM%2F%22&filter%5B%5D=online_boolean%3A%221%22&filter%5B%5D=main_date_str%3A%221910%22&lookfor=torni&type=AllFields",
            },
            {
                "value": "2017",
                "translated": "2017",
                "count": 26,
                "href": "?limit=0&filter%5B%5D=format%3A%220%2FImage%2F%22&filter%5B%5D=building%3A%220%2FHKM%2F%22&filter%5B%5D=online_boolean%3A%221%22&filter%5B%5D=main_date_str%3A%222017%22&lookfor=torni&type=AllFields",
            },
            {
                "value": "1959",
                "translated": "1959",
                "count": 23,
                "href": "?limit=0&filter%5B%5D=format%3A%220%2FImage%2F%22&filter%5B%5D=building%3A%220%2FHKM%2F%22&filter%5B%5D=online_boolean%3A%221%22&filter%5B%5D=main_date_str%3A%221959%22&lookfor=torni&type=AllFields",
            },
            {
                "value": "1981",
                "translated": "1981",
                "count": 23,
                "href": "?limit=0&filter%5B%5D=format%3A%220%2FImage%2F%22&filter%5B%5D=building%3A%220%2FHKM%2F%22&filter%5B%5D=online_boolean%3A%221%22&filter%5B%5D=main_date_str%3A%221981%22&lookfor=torni&type=AllFields",
            },
            {
                "value": "1952",
                "translated": "1952",
                "count": 22,
                "href": "?limit=0&filter%5B%5D=format%3A%220%2FImage%2F%22&filter%5B%5D=building%3A%220%2FHKM%2F%22&filter%5B%5D=online_boolean%3A%221%22&filter%5B%5D=main_date_str%3A%221952%22&lookfor=torni&type=AllFields",
            },
            {
                "value": "1974",
                "translated": "1974",
                "count": 22,
                "href": "?limit=0&filter%5B%5D=format%3A%220%2FImage%2F%22&filter%5B%5D=building%3A%220%2FHKM%2F%22&filter%5B%5D=online_boolean%3A%221%22&filter%5B%5D=main_date_str%3A%221974%22&lookfor=torni&type=AllFields",
            },
            {
                "value": "1918",
                "translated": "1918",
                "count": 21,
                "href": "?limit=0&filter%5B%5D=format%3A%220%2FImage%2F%22&filter%5B%5D=building%3A%220%2FHKM%2F%22&filter%5B%5D=online_boolean%3A%221%22&filter%5B%5D=main_date_str%3A%221918%22&lookfor=torni&type=AllFields",
            },
            {
                "value": "2018",
                "translated": "2018",
                "count": 21,
                "href": "?limit=0&filter%5B%5D=format%3A%220%2FImage%2F%22&filter%5B%5D=building%3A%220%2FHKM%2F%22&filter%5B%5D=online_boolean%3A%221%22&filter%5B%5D=main_date_str%3A%222018%22&lookfor=torni&type=AllFields",
            },
            {
                "value": "1895",
                "translated": "1895",
                "count": 20,
                "href": "?limit=0&filter%5B%5D=format%3A%220%2FImage%2F%22&filter%5B%5D=building%3A%220%2FHKM%2F%22&filter%5B%5D=online_boolean%3A%221%22&filter%5B%5D=main_date_str%3A%221895%22&lookfor=torni&type=AllFields",
            },
            {
                "value": "1976",
                "translated": "1976",
                "count": 20,
                "href": "?limit=0&filter%5B%5D=format%3A%220%2FImage%2F%22&filter%5B%5D=building%3A%220%2FHKM%2F%22&filter%5B%5D=online_boolean%3A%221%22&filter%5B%5D=main_date_str%3A%221976%22&lookfor=torni&type=AllFields",
            },
            {
                "value": "1866",
                "translated": "1866",
                "count": 19,
                "href": "?limit=0&filter%5B%5D=format%3A%220%2FImage%2F%22&filter%5B%5D=building%3A%220%2FHKM%2F%22&filter%5B%5D=online_boolean%3A%221%22&filter%5B%5D=main_date_str%3A%221866%22&lookfor=torni&type=AllFields",
            },
            {
                "value": "1919",
                "translated": "1919",
                "count": 18,
                "href": "?limit=0&filter%5B%5D=format%3A%220%2FImage%2F%22&filter%5B%5D=building%3A%220%2FHKM%2F%22&filter%5B%5D=online_boolean%3A%221%22&filter%5B%5D=main_date_str%3A%221919%22&lookfor=torni&type=AllFields",
            },
            {
                "value": "1958",
                "translated": "1958",
                "count": 18,
                "href": "?limit=0&filter%5B%5D=format%3A%220%2FImage%2F%22&filter%5B%5D=building%3A%220%2FHKM%2F%22&filter%5B%5D=online_boolean%3A%221%22&filter%5B%5D=main_date_str%3A%221958%22&lookfor=torni&type=AllFields",
            },
            {
                "value": "1964",
                "translated": "1964",
                "count": 18,
                "href": "?limit=0&filter%5B%5D=format%3A%220%2FImage%2F%22&filter%5B%5D=building%3A%220%2FHKM%2F%22&filter%5B%5D=online_boolean%3A%221%22&filter%5B%5D=main_date_str%3A%221964%22&lookfor=torni&type=AllFields",
            },
            {
                "value": "2005",
                "translated": "2005",
                "count": 18,
                "href": "?limit=0&filter%5B%5D=format%3A%220%2FImage%2F%22&filter%5B%5D=building%3A%220%2FHKM%2F%22&filter%5B%5D=online_boolean%3A%221%22&filter%5B%5D=main_date_str%3A%222005%22&lookfor=torni&type=AllFields",
            },
        ],
        "category_str_mv": [],
    },
    "status": "OK",
}
