# Generated by Django 1.10.2 on 2017-02-06 13:54


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hkm", "0007_productorder_order_hash"),
    ]

    operations = [
        migrations.AddField(
            model_name="productorder",
            name="form_phase",
            field=models.IntegerField(default=1, verbose_name="Order form phase"),
        ),
    ]
