# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-08 07:08


from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("hkm", "0010_auto_20170207_1330"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productorder",
            name="city",
            field=models.CharField(max_length=255, null=True, verbose_name="City"),
        ),
        migrations.AlterField(
            model_name="productorder",
            name="email",
            field=models.EmailField(max_length=255, null=True, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="productorder",
            name="first_name",
            field=models.CharField(
                max_length=255, null=True, verbose_name="First name"
            ),
        ),
        migrations.AlterField(
            model_name="productorder",
            name="last_name",
            field=models.CharField(max_length=255, null=True, verbose_name="Last name"),
        ),
        migrations.AlterField(
            model_name="productorder",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, null=True, verbose_name="Phone number"
            ),
        ),
        migrations.AlterField(
            model_name="productorder",
            name="postal_code",
            field=models.IntegerField(null=True, verbose_name="Postal code"),
        ),
        migrations.AlterField(
            model_name="productorder",
            name="street_address",
            field=models.CharField(
                max_length=1024, null=True, verbose_name="Street adress"
            ),
        ),
    ]
