# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-08 10:22


import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hkm", "0012_auto_20170208_1218"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productorder",
            name="amount",
            field=models.PositiveIntegerField(
                default=1,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Amount",
            ),
        ),
    ]
