# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-19 10:17


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hkm', '0021_page_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='printproduct',
            name='is_museum_only',
            field=models.BooleanField(default=False, verbose_name='Museum purchase only'),
        ),
    ]
