# Generated by Django 1.10.2 on 2017-11-20 12:55


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hkm", "0028_order_discount_lines"),
    ]

    operations = [
        migrations.AddField(
            model_name="productordercollection",
            name="is_checkout_successful",
            field=models.NullBooleanField(verbose_name="Checkout successful"),
        ),
        migrations.AddField(
            model_name="productordercollection",
            name="is_payment_successful",
            field=models.NullBooleanField(verbose_name="Payment successful"),
        ),
        migrations.AddField(
            model_name="productordercollection",
            name="is_order_successful",
            field=models.NullBooleanField(verbose_name="Order successful"),
        ),
    ]
