# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-12-12 12:35


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hkm', '0034_postal_code_to_charfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printproduct',
            name='name',
            field=models.CharField(choices=[(b'api-poster-gloss-30x40', 'api-poster-gloss-30x40'), (b'api-poster-gloss-40x30', 'api-poster-gloss-40x30'), (b'api-poster-30x40', 'api-poster-30x40'), (b'api-poster-40x30', 'api-poster-40x30'), (b'api-poster-50x70', 'api-poster-50x70'), (b'api-poster-70x50', 'api-poster-70x50'), (b'api-poster-gloss-A4-horizontal', 'api-poster-gloss-A4-horizontal'), (b'api-poster-gloss-A4', 'api-poster-gloss-A4')], max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='productorder',
            name='postal_fees',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Shipping fees'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='printer_presets',
            field=models.TextField(default=b'{"api-poster-gloss-A4": 0, "api-poster-30x40": 0, "api-poster-gloss-30x40": 0, "api-poster-gloss-40x30": 0, "api-poster-40x30": 0, "api-poster-70x50": 0, "api-poster-gloss-A4-horizontal": 0, "api-poster-50x70": 0}', verbose_name='Tulostimen presetit'),
        ),
    ]
