# Generated by Django 1.10.8 on 2018-12-12 12:46


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hkm", "0035_auto_20181212_1435"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="user_group",
            field=models.CharField(
                choices=[
                    ("ALL", "Kaikki"),
                    ("MUSEUM", "Kioskikäyttäjät"),
                    ("NORMAL", "Normaalikäyttäjät"),
                ],
                default="ALL",
                help_text="Käyttäjäryhmä, jolle tarjous on voimassa",
                max_length=20,
                verbose_name="Käyttäjäryhmä",
            ),
        ),
    ]
