# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-09-03 04:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hkm', '0039_collection_is_showcaseable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showcase',
            name='albums',
            field=models.ManyToManyField(to='hkm.Collection', verbose_name='Albums'),
        ),
    ]
