# Generated by Django 1.10.8 on 2020-09-03 04:08


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hkm", "0040_remove_obsolete_image_fields_from_record"),
    ]

    operations = [
        migrations.AlterField(
            model_name="showcase",
            name="albums",
            field=models.ManyToManyField(to="hkm.Collection", verbose_name="Albums"),
        ),
    ]
