# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-11-24 07:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hkm', '0040_auto_20200903_0708'),
        ('hkm', '0040_remove_obsolete_image_fields_from_record'),
    ]

    operations = [
    ]
