# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-18 11:43


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hkm", "0041_update_showcase_albums_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="removal_notification_sent",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Removal notification sent"
            ),
        ),
    ]
