# Generated by Django 1.11.29 on 2022-01-21 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hkm", "0042_add_removal_notification_sent_to_userprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="printer_presets",
            field=models.TextField(
                default='{"api-poster-gloss-30x40": 0, "api-poster-gloss-40x30": 0, "api-poster-30x40": 0, "api-poster-40x30": 0, "api-poster-50x70": 0, "api-poster-70x50": 0, "api-poster-gloss-A4-horizontal": 0, "api-poster-gloss-A4": 0}',
                verbose_name="Tulostimen presetit",
            ),
        ),
    ]
