# Generated by Django 1.11.29 on 2022-01-25 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hkm", "0043_alter_userprofile_printer_presets"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="albums",
            field=models.ManyToManyField(
                blank=True,
                help_text="List of albums for browsing if user is museum",
                to="hkm.Collection",
            ),
        ),
    ]
