# Generated by Django 2.0.13 on 2022-01-26 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hkm", "0045_alter_translations_after_parler_upgrade"),
    ]

    operations = [
        migrations.AlterField(
            model_name="showcase",
            name="albums",
            field=models.ManyToManyField(
                limit_choices_to={"is_showcaseable": True},
                to="hkm.Collection",
                verbose_name="Albums",
            ),
        ),
    ]
