# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 10:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hkm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('prize', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prize')),
                ('width', models.IntegerField(verbose_name='Width')),
                ('height', models.IntegerField(verbose_name='Height')),
                ('paper_quality', models.CharField(max_length=255, verbose_name='Paper quality')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('first_name', models.CharField(max_length=255, verbose_name='First name')),
                ('last_name', models.CharField(max_length=255, verbose_name='Last name')),
                ('email', models.EmailField(max_length=255, verbose_name='Email')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, verbose_name='Phone number')),
                ('street_address', models.CharField(max_length=1024, verbose_name='Street adress')),
                ('postal_code', models.IntegerField(verbose_name='Postal code')),
                ('city', models.CharField(max_length=255, verbose_name='City')),
                ('object_id', models.PositiveIntegerField()),
                ('image_url', models.CharField(max_length=2048, verbose_name='Image URL')),
                ('amount', models.IntegerField(default=1, verbose_name='Amount')),
                ('unit_prize', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Unit prize')),
                ('total_prize', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total prize')),
                ('datetime_confirmed', models.DateTimeField(blank=True, null=True, verbose_name='Confirmed')),
                ('datetime_checkout_started', models.DateTimeField(blank=True, null=True, verbose_name='Checkout started')),
                ('datetime_checkout_ended', models.DateTimeField(blank=True, null=True, verbose_name='Checkout ended')),
                ('is_checkout_successful', models.NullBooleanField(verbose_name='Checkout succesful')),
                ('datetime_order_started', models.DateTimeField(blank=True, null=True, verbose_name='Order started')),
                ('datetime_order_ended', models.DateTimeField(blank=True, null=True, verbose_name='Order ended')),
                ('is_order_successful', models.NullBooleanField(verbose_name='Order succesful')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.ContentType')),
                ('record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hkm.Record', verbose_name='Record')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
