# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-06 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hkm', '0006_auto_20170206_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorder',
            name='order_hash',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Randomized order identifier phrase'),
        ),
    ]
