name: Continuous integration

on:
  push:
    branches: [master]
  pull_request:


env:
  SECRET_KEY: topsecret123


jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:10
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          POSTGRES_USER: kuvaselaamo
          POSTGRES_PASSWORD: kuvaselaamo
          POSTGRES_DB: kuvaselaamo

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python 2.7
        uses: actions/setup-python@v2
        with:
          python-version: '2.7'

      - name: Cache pip packages
        uses: actions/cache@v2
        env:
          cache-name: cache-pip-modules
        with:
          path: ~/.pip-cache
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/requirements.txt') }}-${{ hashFiles('**/requirements-dev.txt') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install dependencies
        run: |
          pip install -r requirements.txt -r requirements-dev.txt codecov
      - name: Run tests
        run: pytest -ra -vv --cov=.
        env:
          DATABASE_URL: postgres://kuvaselaamo:kuvaselaamo@localhost:5432/kuvaselaamo

      - name: Coverage
        run: codecov
