name: Build & Production
on:
  push:
    tags:
      - 'release-*'

env:
  CONTAINER_REGISTRY: ghcr.io
  CONTAINER_REGISTRY_USER: ${{ secrets.GHCR_CONTAINER_REGISTRY_USER }}
  CONTAINER_REGISTRY_PASSWORD: ${{ secrets.GHCR_TOKEN }}
  CONTAINER_REGISTRY_REPO: ghcr.io/city-of-helsinki/${{ github.event.repository.name }}
  REPO_NAME: ${{ github.event.repository.name }}
  KUBECONFIG_RAW: ${{ secrets.KUBECONFIG_RAW_STABLE }}
  BUILD_ARTIFACT_FOLDER: 'build_artifacts'
  SERVICE_ARTIFACT_FOLDER: 'service_artifacts'
  APP_MIGRATE_COMMAND: /app/.prod/on_deploy.sh
  SERVICE_PORT: "8080"
  K8S_REQUEST_CPU: 100m
  K8S_REQUEST_RAM: 200Mi
  K8S_LIMIT_CPU: 800m
  K8S_LIMIT_RAM: 1Gi
  K8S_REPLICACOUNT: 2

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v2
      - name: Build
        uses: andersinno/kolga-build-action@v2

  production:
    runs-on: ubuntu-latest
    needs: build
    name: Production
    steps:
      - uses: actions/checkout@v2
      - uses: andersinno/kolga-setup-action@v2

      - name: Deploy
        uses: andersinno/kolga-deploy-action@v2
        with:
          track: 'stable'
        env:
          K8S_NAMESPACE: ${{ secrets.K8S_NAMESPACE_STABLE }}
          K8S_ADDITIONAL_HOSTNAMES: ${{ secrets.K8S_ADDITIONAL_HOSTNAMES }}
          ENVIRONMENT_URL: https://${{ secrets.ENVIRONMENT_URL_STABLE }}
          K8S_SECRET_ALLOWED_HOSTS: "*"
          K8S_SECRET_DEBUG: 0
          K8S_SECRET_SKIP_DATABASE_CHECK: 1
          K8S_SECRET_SECRET_KEY: ${{ secrets.GH_STABLE_DJANGO_SECRET_KEY }}
          K8S_SECRET_VERSION: ${{ github.sha }}
          K8S_SECRET_ADMIN_USER_PASSWORD: ${{ secrets.STABLE_ADMIN_USER_PASSWORD }}
          K8S_SECRET_HKM_DEFAULT_FROM_EMAIL: "no-reply@hel.fi"
          K8S_SECRET_HKM_FEEDBACK_NOTIFICATION_EMAILS: ${{ secrets.STABLE_HKM_FEEDBACK_NOTIFICATION_EMAILS }}
          K8S_SECRET_EMAIL_BACKEND: "anymail.backends.mailgun.EmailBackend"
          K8S_SECRET_MAIL_MAILGUN_KEY: ${{ secrets.GH_STABLE_MAILGUN_API_KEY }}
          K8S_SECRET_MAIL_MAILGUN_DOMAIN: "hel.fi"
          K8S_SECRET_MAIL_MAILGUN_API: "https://api.eu.mailgun.net/v3"
          K8S_SECRET_HKM_PBW_API_ENDPOINT: "https://payform.bambora.com/pbwapi"
          K8S_SECRET_HKM_PBW_API_KEY: ${{ secrets.GH_STABLE_PBW_API_KEY }}
          K8S_SECRET_HKM_PBW_SECRET_KEY: ${{ secrets.GH_STABLE_PBW_SECRET_KEY }}
          K8S_SECRET_HKM_MY_DOMAIN: "https://helsinkikuvia.prod.kuva.hel.ninja"
          K8S_SECRET_HKM_PRINTMOTOR_USERNAME: ${{ secrets.GH_STABLE_PRINTMOTOR_USERNAME }}
          K8S_SECRET_HKM_PRINTMOTOR_PASSWORD: ${{ secrets.GH_STABLE_PRINTMOTOR_PASSWORD }}
          K8S_SECRET_HKM_PRINTMOTOR_API_KEY: ${{ secrets.GH_STABLE_PRINTMOTOR_API_KEY }}
          K8S_SECRET_HKM_PRINTMOTOR_API_ENDPOINT: "https://api.printmotor.io/api/v1/order"
          K8S_SECRET_DEFAULT_FILE_STORAGE: "storages.backends.azure_storage.AzureStorage"
          K8S_SECRET_AZURE_BUCKET_ACCOUNT_NAME: ${{ secrets.STABLE_AZURE_BUCKET_ACCOUNT_NAME }}
          K8S_SECRET_AZURE_BUCKET_CREDENTIALS: ${{ secrets.STABLE_AZURE_BUCKET_CREDENTIALS }}
          K8S_SECRET_AZURE_BUCKET_NAME: ${{ secrets.STABLE_AZURE_BUCKET_NAME }}
          K8S_SECRET_ENABLE_ANALYTICS: 1
          K8S_SECRET_HKM_POSTAL_FEES: ${{ secrets.HKM_POSTAL_FEES }}
          K8S_SECRET_DATABASE_HOST: ${{ secrets.K8S_SECRET_DATABASE_HOST_STABLE }}
          K8S_SECRET_DATABASE_URL: ${{ secrets.K8S_SECRET_DATABASE_URL_STABLE }}
          K8S_SECRET_DATABASE_PORT: ${{ secrets.K8S_SECRET_DATABASE_PORT_STABLE }}
          K8S_SECRET_DATABASE_DB: ${{ secrets.K8S_SECRET_DATABASE_DB_STABLE }}
          K8S_SECRET_DATABASE_USERNAME: ${{ secrets.K8S_SECRET_DATABASE_USERNAME_STABLE }}
          K8S_SECRET_DATABASE_PASSWORD: ${{ secrets.K8S_SECRET_DATABASE_PASSWORD_STABLE }}
